### ISSUE TITLE
Sites with word lists

### ISSUE THREAD

**Issue by ajdavidl** [LilithHafner/WordLists.jl#7]
Hi,

I found some sites on the internet containing lists of words for some languages. A few examples are:
- [https://es.wikwik.org/todaspalabras.htm](https://es.wikwik.org/todaspalabras.htm);
- [https://www.listasdepalabras.es/todaspalabras.htm](https://www.listasdepalabras.es/todaspalabras.htm);
- [https://it.wikwik.org/tutteleparole.htm](https://it.wikwik.org/tutteleparole.htm);
- [https://www.listediparole.it/tutteleparole.htm](https://www.listediparole.it/tutteleparole.htm).

There are lists for English, Spanish, Italian, French, Portuguese, German, Dutch and Romanian.

Would you like me to do some pull requests with those lists?

**Comment by LilithHafner** [comment]
That would be lovely, thank you!

**Comment by ajdavidl** [comment]
We added lists of Italian, French, German and Dutch languages. We also updated the lists of Spanish and Portuguese languages.

**Comment by LilithHafner** [comment]
Thank you so much!
